# Generated by Django 4.0.6 on 2022-07-21 02:41

from django.db import migrations

def populate_article_status(apps, schemaeditor):
    status_types = {
        "published": "",
        "pending review": "",
        "revision requested": "",
        "denied": "",
        "draft": "",
    }
    Status = apps.get_model("articles", "Status")
    for name, desc in status_types.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_status_article_status'),
    ]

    operations = [
        migrations.runPython(populate_article_status),
    ]
